LOOP	LDA	#0
	STA	J	.INIT J VALUE WITH 0 BEFORE INNER LOOP
	J	INLOOP	.GO INTO INNER LOOP
MOVEI	LDX	I
	TIX	STRLEN	.COMPARE I WITH STRLEN(3)
	JEQ	FIN	.IF EQUALS, FINISH THE ENTIRE LOOP
	STX	I
	J	LOOP	.I <= 2 YET, GO ON THE LOOP
	
INLOOP	LDX	I
	LDCH	ANSWER,X
	STA	C1	.C1 = ANSWER[I], RIGHTMOST 3BYTE FOR C1
	LDX	J
	LDCH	GUESS,X .LOAD 1 BYTE CHAR TO RIGHTMOSTE 1BYTE OF A REG
	COMP	C1	.COMPARE ANS[I] WITH GUES[J]
	JEQ	EQUAL	.IF IT EQUALS, JUMP EQUAL
	TIX	STRLEN  .COMPARE J WITH STRLEN(3)
	JEQ	ADDOUT	.IF GUESS[J,X==3], COMPARE IS FINISHED, ++OUT
	STX	J
	J	INLOOP	.J <= 2 FOR NOW

EQUAL	LDA	I
	COMP	J
	JEQ	ADDRS	.IF I EQUALS J, JUMP ADDR_STRIKE
	J	ADDRB	.IF I != J, JUMP ADDR_BALL

ADDONE	LDA	@ADDR
	ADD	#1
	STA	@ADDR
	J	MOVEI	.ADDING STRIKE OR BALL FINISHED, GO BACK FOR ++I

ADDRS	LDA	#STK
	STA	ADDR
	J	ADDONE	.IF ADDR_STRIKE FIN, JUMP ADDONE

ADDRB	LDA	#BALL
	STA	ADDR
	J	ADDONE	.IF ADDR_BALL FIN, JUMP ADDONE

ADDOUT	LDA	OUT
	ADD	#1
	STA	OUT
	J	MOVEI	.IF ADDR_O FIN, TIME TO PROCESS ++I

FIN	LDA	I	.NOTHING MUCH HAHA
	ADD	#1
	STA	I

SAME	RESW	1	
DIFF	RESW	1
STKF	RESW	1

STK	RESW	1
OUT	RESW	1
BALL	RESW	1

ANSWER	BYTE	C'312'
GUESS	BYTE	C'312'

STRLEN	WORD	3
I	RESW	1
J	RESW	1
ADDR	RESW	1
C1	RESW	1
