LOOP	LDA	#0
	STA	J	.INIT J VALUE WITH 0 BEFORE INNER LOOP
	STA	SAME	.INIT INT SAME VAL WITH FALSE(0)
	J	INLOOP	.GO INTO INNER LOOP
MOVEI	LDA	I
	ADD	#1
	STA	I	.++I
	LDA	I
	COMP	STRLEN	.COMPARE I WITH STRLEN(3)
	JEQ	FIN	.IF EQUALS, FINISH THE ENTIRE LOOP
	J	LOOP	.I <= 2 YET, GO ON THE LOOP

FIN	LDA	I	.NOTHING MUCH HAHA
	ADD	A
	STA	I

INLOOP	LDA	I
	COMP	STR,J	.COMPARE ANS[I] WITH GUES[J]
	JEQ	EQUAL	.IF IT EQUALS, JUMP EQUAL
	LDA	J
	ADD	#1
	STA	J	.++J
	COMP	STRLEN	.COMPARE J WITH STRLEN(3)
	JEQ	ADDOUT	.IF GUESS[J==3], COMPARE IS FINISHED, ++OUT
	J	INLOOP	.J <= 2 FOR NOW

EQUAL	LDA	I
	COMP	J
	JEQ	ADDRS	.IF I EQUALS J, JUMP ADDR_STRIKE
	J	ADDRB	.IF I != J, JUMP ADDR_BALL

ADDONE	LDA	@ADDR
	ADD	#1
	STA	@ADDR
	J	MOVEI	.ADDING STRIKE OR BALL FINISHED, GO BACK FOR ++I

ADDRS	LDA	#STK
	STA	ADDR
	J	ADDONE	.IF ADDR_STRIKE FIN, JUMP ADDONE

ADDRB	LDA	#BALL
	STA	ADDR
	J	ADDONE	.IF ADDR_BALL FIN, JUMP ADDONE

ADDOUT	LDA	OUT
	ADD	#1
	STA	OUT
	J	MOVEI	.IF ADDR_O FIN, TIME TO PROCESS ++I

SAME	RESW	1	
DIFF	RESW	1
STKF	RESW	1

STK	RESW	1
OUT	RESW	1
BALL	RESW	1

ANSWER	BYTE	C'734'
GUESS	BYTE	C'123'

STRLEN	WORD	3
I	RESW	1
J	RESW	1
ADDR	RESW	1
